### ISSUE TITLE
"You have unread Chat messages" in emails, but I don't

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-server#10]
Hi Ed. My emails from Freegle now have a banner at the top that says "You have unread Chat messages. Click here." This sounds like a useful feature. But I *don't* have any unread chats on the site. That is, there is no number badge over the Chats icon, nothing showing as unread in Chats. I have clicked "Mark all read" in any case, and even shown hidden/blocked chats and then clicked "Mark all read" again, but still the emails arrive saying I have unread chats.

Any ideas?

**Comment by edwh** [comment]
You're right.  Bad fix, which I've now removed until I can turn it into 
a good fix.


------ Original Message ------
From "John Veness" ***@***.***>
To "Freegle/iznik-server" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 12/09/2024 14:16:05
Subject [Freegle/iznik-server] "You have unread Chat messages" in 
emails, but I don't (Issue #10)

**Comment by edwh** [comment]
Because of the way we construct emails, the intended function is too hard to implement.  I can't see myself having time to do it any time soon, so I've removed it and will close this issue.
