### ISSUE TITLE
Does not accept complex password

### ISSUE THREAD

**Issue by nicksellen** [Freegle/iznik-server#2]
I cannot login if I set my password to:

```
fztnu;~F*.ffe_eHE4B?>\-|P&GcV{l4_f_CdVf6?{:[LY.sQDV}G_E%dAoCM''.|3K<'w2,!0N]A!:p
```

I have reset it to a simpler one using the "forgot password" feature now.

**Comment by edwh** [comment]
This was actually a client issue - we had a max password length of 40 on the login form but no such limit on the settings page.  I've increased the limit to 255 and applied it consistently.
