### ISSUE TITLE
Move away from HHVM to PHP 7

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-server#4]
Facebook are discontinuing support for PHP in HHVM.  We want to stick with PHP rather than get tied to Hack because that is more widely used and therefore more attractive to volunteers.  The original reason for going with HHVM was that it was much better than PHP for scalability and performance, but things have moved on and PHP 7 is much improved.

The first stage is to get the UT running with PHP 7 on Docker.

**Comment by codepotato** [comment]
Could also help out on this front @edwh 

Are there any particular areas that have been coded with HHVM in mind? Or just a general sweep of the whole app?

**Comment by edwh** [comment]
This one is well in hand, but I hadn't updated the issue.  I've switched over the front-end web side to use PHP 7 now.  There are still some of the backend servers that are using HHVM, which I'll tidy up.  There's nothing that's fundamentally reliant on HHVM, though.

Generally the barrier to entry for the server side is higher - it's not using a standard PHP framework, and some of the issues to do with scalability and performance won't be obvious.  So if you're keen to get involved, and especially as you have front-end skills, the client project is a good place to start.  But there are some areas such as the emails....so I'll go and comment on that one now.

**Comment by edwh** [comment]
Done.
