### ISSUE TITLE
Email subject line suffix ~~~~~--~~~~-~-~---~-~~---

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-server#5]
Starting in last day or so (7 Mar 2019?) all my OFFER and WANTED emails from you have ~~~~~--~~~~-~-~---~-~~--- as a suffix on the subject line. This means email clients cannot show as much of a message body preview as they used to. I'm not sure if this is intentional?

![](https://i.imgur.com/dqN0DIg.png)

**Comment by edwh** [comment]
Hi John,

Yes, it's intentional.  It's part of some investigation we're doing into 
when emails are delivered to the inbox folder vs spam.

Sorry for any inconvenience.  It will probably be around for a month or 
so.

Edward

------ Original Message ------

**Comment by edwh** [comment]
We're leaving this indefinitely, as it is useful in handling support queries from users with multiple accounts.
