### ISSUE TITLE
Plain text transactional emails

### ISSUE THREAD

**Issue by prcmt** [Freegle/iznik-server#8]
I've seen the recent email asking for volunteers to spruce up the email. I'm not in a position to help, but wanted to say that I'd quite like the option to receive plain text emails for transactional content.

Newsletters we want to look beautiful! But for new messages, offers, etc. personally I like just some nice clear text.

**Comment by edwh** [comment]
Thanks for the issue.  We do include text bodyparts in the mails we 
send, or at least the ones I've checked.  Your email client may well 
have an option which allows you to view those rather than the HTML ones?

------ Original Message ------

**Comment by prcmt** [comment]
Thanks for pointing that out, really should've thought of it myself. :)

**Comment by edwh** [comment]
Some of the text versions may be a bit lame, though, as they get looked at less.  So if you find some which need work, do please let me know.
