### ISSUE TITLE
Over-zealous censoring of numbers

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-server#9]
I'm not sure if this is a client or server issue, so I'm taking a guess it fits here!

Numbers in messages get replaced with "*", presumably to try and stop people sharing their phone number publicly, but I think the algorithm needs a bit of tweaking. For example, I saw the following message today:

> `***-*** must be the model no.  Input  100–240 V-500Hz *** mA. Output =32 V   ***mA.
`

Thanks!

**Comment by edwh** [comment]
I think the censoring only applies when you're logged out, to stop phone numbers etc leaking out onto the web.  If you're logged in it should show.  Does it?

It's nigh on impossible to get this right, as people don't always format phone numbers in a way that lends itself to a neat regular expression.  So we err on the side of excessive masking for logged out users.

**Comment by JohnVeness** [comment]
I'm seeing the asterisks while **logged into** the site. Luckily I have emails enabled, which *don't* censor the numbers, so I can see the details that way, just not on the site.

**Comment by edwh** [comment]
Can you give me an example URL for a message which shows that?

**Comment by JohnVeness** [comment]
https://www.ilovefreegle.org/message/104022956

**Comment by edwh** [comment]
@JohnVeness Thanks - fix applied.
